#2(a)
patients_list_columns = names(patients)
#2(b)
patients_rows = dim(patients)
#2(c)
paitents_sum = summary(patients)
#2(d)
age_mean = mean(patients$age)
#2(e)
age_per_gender_mean = aggregate(age~gender, data = patients, mean)
#2(f)
bp_of_age_and_marital_staus_per_patient = boxplot(patients$age~patients$marriage, main = "Boxplot of the Age and Marital Status of each Patient", xlab = "Marital Status of each Patient", ylab = "Age of each Patient")
#2(g)
bp_of_height_and_weight_range_per_patient = boxplot(patients$height~patients$obese, main = "Boxplot of the height and range of weight of the Patients", xlab = "Weight renage of the Patients", ylab = "Height of the Patients")
#2(h)
pie_marital_status =  pie(table(patients$marriage))
#2(i)
hist_totalchol =  hist(patients$totalchol, main = "Histogram of the total cholesterol of the Patients", xlab = "Total Cholesterol", ylab = "Number of Patients")
#3(b)
R_function = f = function(x)
{
  y=(x-mean(x))/sqrt(var(x))
  return(sqrt(var(y)))
}
x=c(1:100)
f(x)